name: todoList

services:
  postgres:
    container_name: postgres2
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cenk
      - POSTGRES_PASSWORD=luffy
      - POSTGRES_DB=db
